-- 0009_notifications.sql
-- Phase 5A: notifications table for in-app notification bell.
-- Represents notification events generated by the system.
-- Designed to be channel-neutral: is_read tracks in-app dismissal only.
-- A future SMS/email delivery phase will read from this table and track
-- delivery state separately (e.g. notification_deliveries). No delivery
-- columns belong here.
-- All inserts come from security definer RPCs (added in 0010).
-- Apply in Supabase SQL Editor (cloud only).

-- ---------------------------------------------------------------------------
-- notifications
-- ---------------------------------------------------------------------------
create table notifications (
  id         uuid        primary key default uuid_generate_v4(),
  club_id    uuid        not null references clubs(id) on delete cascade,
  user_id    uuid        not null references profiles(id) on delete cascade,
  kind       text        not null
               check (kind in (
                 'reservation_confirmed',
                 'reservation_cancelled_by_admin',
                 'event_cancelled',
                 'event_joined'
               )),
  body       text        not null,
  is_read    boolean     not null default false,
  metadata   jsonb,
  created_at timestamptz not null default now()
);

create index notifications_user_created_idx
  on notifications (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table notifications enable row level security;

-- Users may read only their own notifications.
create policy "own_select"
  on notifications for select
  using (user_id = auth.uid());

-- Users may update only their own notifications (mark as read).
-- No INSERT policy — all inserts are via security definer RPCs.
create policy "own_update"
  on notifications for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
