-- 0211_member_notes_schema_reconciliation.sql
-- Phase 45C1A — reconciles this repository's migration history with the
-- LIVE production schema for public.member_notes and its three write RPCs
-- (add_member_note, update_member_note, archive_member_note).
--
-- BACKGROUND (see the Phase 45C1A audit report for the full evidence trail):
-- migrations 0075/0077 created member_notes with a `content` column and
-- add_member_note/update_member_note/archive_member_note taking `p_content`.
-- At some point before Phase 34A4A (migration 0132), PRODUCTION was changed
-- directly — content -> body, plus new is_archived/archived_by columns —
-- entirely out-of-band, never captured in any migration file. Migration
-- 0132 already reconciled the READ side (get_member_notes and others) by
-- copying live `pg_get_functiondef` output verbatim, and its own comments
-- say so explicitly ("PRODUCTION pg_get_functiondef is the verified source
-- of truth, not 0077"). The WRITE side (the three functions this migration
-- fixes) was explicitly left untouched by 0132 ("deliberately left
-- admin-only and unwidened") and has remained uncaptured until now.
--
-- This migration is designed to safely converge BOTH:
--   STATE A — a fresh replay of 0001-0210 (content, no is_archived/
--             archived_by, p_content functions, add_member_note returns
--             public.member_notes)
--   STATE B — current live production (already body/is_archived/
--             archived_by/p_body/json — this migration's job is to become
--             a no-op there, not to change anything already correct)
-- to the exact same canonical, verified-live contract. Every DDL step is
-- idempotent and conditional; nothing here assumes which state it's
-- running against.
--
-- Scope is deliberately narrow: member_notes table shape + the three write
-- RPCs only. get_member_notes is NOT touched (0132 already made it
-- correct). RLS, grants on unrelated objects, and every other domain
-- (payments/reservations/lessons/waivers/memberships) are untouched.
--
-- Apply in Supabase SQL Editor (cloud only). Do NOT edit this file after
-- applying.

begin;

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. member_notes — content/body column convergence
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Exactly one of {content, body} must exist before this runs. Both existing,
-- or neither existing, means this table is in a state this migration was
-- never designed for — stop rather than guess which column holds the real
-- data.

do $$
declare
  v_has_content boolean;
  v_has_body    boolean;
begin
  select exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'member_notes' and column_name = 'content'
  ) into v_has_content;

  select exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'member_notes' and column_name = 'body'
  ) into v_has_body;

  if v_has_content and v_has_body then
    raise exception 'member_notes_ambiguous_column_state: both content and body columns exist on public.member_notes — cannot safely determine which holds canonical data. Manual review required; this migration refuses to guess.';
  end if;

  if not v_has_content and not v_has_body then
    raise exception 'member_notes_missing_column_state: neither content nor body columns exist on public.member_notes — table is in an unexpected state. Manual review required; this migration refuses to guess.';
  end if;

  if v_has_content then
    -- STATE A (fresh replay): rename in place. RENAME COLUMN is an instant
    -- metadata-only operation — preserves every row's text, id, timestamps,
    -- and the column's NOT NULL constraint unchanged. Postgres also
    -- automatically updates the inline CHECK constraint's internal
    -- expression to reference the new column name (the constraint's OLD
    -- auto-generated name, e.g. member_notes_content_check, is NOT
    -- renamed to match — that stale name is found and dropped by name-
    -- independent lookup in step 3 below, not assumed here).
    alter table public.member_notes rename column content to body;
  end if;
  -- else: STATE B already has `body`, nothing to do here.
end $$;

-- Canonical body is NOT NULL. Renaming an already-NOT-NULL column preserves
-- that (state A); state B's body is already NOT NULL per the live schema.
-- This statement is idempotent either way — SET NOT NULL on an
-- already-NOT-NULL column is a harmless no-op, not an error.
alter table public.member_notes alter column body set not null;

-- ═══════════════════════════════════════════════════════════════════════════
-- 1a. member_notes — member_id FK convergence (ON DELETE CASCADE)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Verified live contract: member_notes_member_id_fkey is
-- FOREIGN KEY (member_id) REFERENCES profiles(id) ON DELETE CASCADE.
-- Migration 0075 created member_id with NO ON DELETE clause at all
-- (defaults to NO ACTION) — an out-of-band production change added CASCADE
-- at some point, never captured in any migration file, exactly like the
-- content->body rename above. This block detects the ACTUAL delete-action
-- semantics of whichever FK constraint currently exists on member_id via
-- pg_constraint.confdeltype ('c' = cascade), not by assumed constraint
-- name, and only acts when it is not already canonical:
--   - FK absent entirely            -> add it as canonical directly.
--   - FK exists, confdeltype <> 'c' -> drop (by its real, looked-up name;
--                                      never CASCADE on the DROP itself)
--                                      and recreate as canonical.
--   - FK exists, confdeltype = 'c'  -> already canonical; no-op.
-- No row data or member_id value is ever touched — this only ever
-- drops/adds the CONSTRAINT, never touches column data.
do $$
declare
  v_member_id_attnum smallint;
  v_conname           text;
  v_confdeltype       char;
begin
  select att.attnum into v_member_id_attnum
    from pg_attribute att
    join pg_class     rel on rel.oid = att.attrelid
    join pg_namespace ns  on ns.oid  = rel.relnamespace
   where ns.nspname = 'public' and rel.relname = 'member_notes' and att.attname = 'member_id';

  select con.conname, con.confdeltype
    into v_conname, v_confdeltype
    from pg_constraint con
    join pg_class      rel on rel.oid = con.conrelid
    join pg_namespace  ns  on ns.oid  = rel.relnamespace
   where ns.nspname = 'public'
     and rel.relname = 'member_notes'
     and con.contype = 'f'  -- FOREIGN KEY constraints only
     and con.conkey = array[v_member_id_attnum]
   limit 1;

  if v_conname is null then
    -- No FK on member_id at all (unexpected, but handled) — add canonical.
    alter table public.member_notes
      add constraint member_notes_member_id_fkey
      foreign key (member_id) references public.profiles(id) on delete cascade;
  elsif v_confdeltype <> 'c' then
    -- STATE A: FK exists but is NO ACTION (0075's original, uncaptured
    -- shape) — replace only this FK with the canonical ON DELETE CASCADE.
    execute format('alter table public.member_notes drop constraint %I', v_conname);
    alter table public.member_notes
      add constraint member_notes_member_id_fkey
      foreign key (member_id) references public.profiles(id) on delete cascade;
  end if;
  -- else (v_confdeltype = 'c'): STATE B already canonical — no-op.
end $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. member_notes — body CHECK constraints
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Drop ONLY the specific legacy CHECK constraint 0075 created inline:
-- `content text not null check (length(btrim(content)) > 0)`. After the
-- content->body rename above, Postgres automatically rewrites this
-- constraint's STORED expression to reference the new column name, so on
-- STATE A it now reads `length(btrim(body)) > 0` under whatever
-- auto-generated name Postgres originally gave it (unverifiable without a
-- live query, hence no assumed name). That expression is fingerprinted by
-- its FUNCTION NAMES — btrim(body) combined with length(...) — which is
-- catalog-semantically distinct from the canonical
-- member_notes_body_nonempty check added below (char_length(trim(body))),
-- which uses the opposite function pairing. This match is robust to
-- whitespace/parenthesization differences (a regex on the function calls,
-- not the literal formatted string) and, critically, will NEVER match any
-- other/future/unrelated CHECK constraint someone adds to member_notes
-- later — unlike a blanket "drop everything not in this name list" loop,
-- which this migration deliberately does NOT use.
--
-- The `length` match uses `\m` (PostgreSQL ARE "beginning of word"), not
-- `\b` — in PostgreSQL's regex dialect `\b` is the BACKSPACE character, not
-- a word-boundary escape (those are `\m`/`\M`/`\y`). `\mlength` still
-- correctly excludes `char_length` from matching: PostgreSQL treats
-- underscore as a word character, so `_length` inside `char_length` is not
-- a word start, and only a true `length(` call-site fingerprint matches.
do $$
declare
  v_con record;
begin
  for v_con in
    select con.oid, con.conname
      from pg_constraint con
      join pg_class      rel on rel.oid = con.conrelid
      join pg_namespace  ns  on ns.oid  = rel.relnamespace
     where ns.nspname = 'public'
       and rel.relname = 'member_notes'
       and con.contype = 'c'  -- CHECK constraints only; never touches PK/FK
       and con.conname not in ('member_notes_body_length', 'member_notes_body_nonempty')
       and pg_get_constraintdef(con.oid) ~* 'btrim\s*\(\s*body\s*\)'
       and pg_get_constraintdef(con.oid) ~* '\mlength\s*\('
  loop
    execute format('alter table public.member_notes drop constraint %I', v_con.conname);
  end loop;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint con
      join pg_class     rel on rel.oid = con.conrelid
      join pg_namespace ns  on ns.oid  = rel.relnamespace
     where ns.nspname = 'public' and rel.relname = 'member_notes'
       and con.conname = 'member_notes_body_nonempty'
  ) then
    alter table public.member_notes
      add constraint member_notes_body_nonempty check (char_length(trim(body)) > 0);
  end if;

  if not exists (
    select 1 from pg_constraint con
      join pg_class     rel on rel.oid = con.conrelid
      join pg_namespace ns  on ns.oid  = rel.relnamespace
     where ns.nspname = 'public' and rel.relname = 'member_notes'
       and con.conname = 'member_notes_body_length'
  ) then
    alter table public.member_notes
      add constraint member_notes_body_length check (char_length(body) <= 2000);
  end if;
end $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. member_notes — is_archived
-- ═══════════════════════════════════════════════════════════════════════════
--
-- ADD COLUMN IF NOT EXISTS with NOT NULL + DEFAULT false is safe and
-- efficient even against a populated table (Postgres 11+ stores the default
-- as column metadata rather than rewriting every row). A no-op on state B,
-- which already has this column per the verified live contract.

alter table public.member_notes
  add column if not exists is_archived boolean not null default false;

-- Backfill: any row already archived under the old archived_at-only
-- mechanism must be tagged is_archived = true. Never invents an
-- archived_at value where none exists — this only ever sets is_archived
-- FROM an existing archived_at, never the reverse. A no-op on state B
-- (already internally consistent per the verified live contract).
update public.member_notes
   set is_archived = true
 where archived_at is not null
   and is_archived = false;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. member_notes — archived_by
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.member_notes
  add column if not exists archived_by uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint con
      join pg_class     rel on rel.oid = con.conrelid
      join pg_namespace ns  on ns.oid  = rel.relnamespace
     where ns.nspname = 'public' and rel.relname = 'member_notes'
       and con.conname = 'member_notes_archived_by_fkey'
  ) then
    alter table public.member_notes
      add constraint member_notes_archived_by_fkey
      foreign key (archived_by) references public.profiles(id) on delete set null;
  end if;
end $$;

-- id, club_id, author_id, author_name_snapshot, created_at, archived_at are
-- NOT touched by this migration at all — no rename, no retype, no
-- constraint change, no data rewrite. Their existing FK/PK constraints
-- (member_notes_pkey, member_notes_club_id_fkey, member_notes_author_id_fkey)
-- are left exactly as 0075 defined them. member_id's FK is the one
-- deliberate exception — its ON DELETE action is converged to the verified
-- live canonical (CASCADE) by section 1a above, since this migration's
-- whole purpose is making history and live production agree on the SAME
-- schema, not just the parts that were easy.

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. add_member_note — DROP + CREATE
-- ═══════════════════════════════════════════════════════════════════════════
-- Requires DROP: both the parameter name (p_content -> p_body) and the
-- return type (public.member_notes -> json) change, and a return-type
-- change alone already cannot be done via CREATE OR REPLACE FUNCTION
-- (Postgres refuses with "cannot change return type of existing function"
-- — the same reason 0075 itself needed DROP for get_members' RETURNS TABLE
-- change). A live pg_depend check for this function returned zero rows —
-- RESTRICT is used anyway, never CASCADE, so this fails loudly rather than
-- silently taking down anything unexpected if that check was incomplete.

drop function if exists public.add_member_note(uuid, text) restrict;

create function public.add_member_note(
  p_member_id uuid,
  p_body      text
)
returns json
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor       public.profiles%rowtype;
  v_target      public.profiles%rowtype;
  v_body        text;
  v_author_name text;
  v_result      public.member_notes%rowtype;
begin
  select pr.* into v_actor from public.profiles pr where pr.id = auth.uid();
  if not found then raise exception 'not_authenticated'; end if;
  if v_actor.role <> 'admin' then raise exception 'insufficient_role'; end if;

  v_body := trim(coalesce(p_body, ''));
  if length(v_body) = 0 then
    raise exception 'body_empty';
  end if;
  if length(v_body) > 2000 then
    raise exception 'body_too_long';
  end if;

  select pr.* into v_target from public.profiles pr
   where pr.id      = p_member_id
     and pr.club_id = v_actor.club_id;
  if not found then raise exception 'member_not_found'; end if;

  v_author_name := nullif(trim(concat_ws(' ', v_actor.first_name, v_actor.last_name)), '');
  if v_author_name is null then
    v_author_name := 'Admin';
  end if;

  insert into public.member_notes (
    club_id, member_id, author_id, author_name_snapshot, body
  ) values (
    v_actor.club_id,
    p_member_id,
    auth.uid(),
    v_author_name,
    v_body
  ) returning * into v_result;

  insert into public.audit_log (club_id, actor_id, action, target_type, target_id, metadata)
  values (
    v_actor.club_id, auth.uid(), 'add_member_note', 'member_note', v_result.id,
    jsonb_build_object('member_id', p_member_id, 'note_id', v_result.id)
  );

  return json_build_object(
    'id',                   v_result.id,
    'member_id',            v_result.member_id,
    'author_id',            v_result.author_id,
    'author_name_snapshot', v_result.author_name_snapshot,
    'body',                 v_result.body,
    'is_archived',          v_result.is_archived,
    'created_at',           v_result.created_at,
    'updated_at',           v_result.updated_at,
    'archived_at',          v_result.archived_at,
    'archived_by',          v_result.archived_by
  );
end;
$$;

alter function public.add_member_note(uuid, text) owner to postgres;
revoke execute on function public.add_member_note(uuid, text) from public, anon;
grant  execute on function public.add_member_note(uuid, text) to authenticated;
grant  execute on function public.add_member_note(uuid, text) to service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. update_member_note — DROP + CREATE
-- ═══════════════════════════════════════════════════════════════════════════
-- Requires DROP: the named parameter changes p_content -> p_body (return
-- type is unchanged, void -> void). Same zero-dependency / RESTRICT-only
-- reasoning as add_member_note above.

drop function if exists public.update_member_note(uuid, text) restrict;

create function public.update_member_note(
  p_note_id uuid,
  p_body    text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor    public.profiles%rowtype;
  v_note     public.member_notes%rowtype;
  v_new_body text;
begin
  select pr.* into v_actor from public.profiles pr where pr.id = auth.uid();
  if not found then raise exception 'not_authenticated'; end if;
  if v_actor.role <> 'admin' then raise exception 'insufficient_role'; end if;

  v_new_body := trim(coalesce(p_body, ''));
  if length(v_new_body) = 0 then
    raise exception 'body_empty';
  end if;
  if length(v_new_body) > 2000 then
    raise exception 'body_too_long';
  end if;

  select mn.* into v_note from public.member_notes mn
   where mn.id      = p_note_id
     and mn.club_id = v_actor.club_id;
  if not found then raise exception 'note_not_found'; end if;
  if v_note.is_archived then raise exception 'note_archived'; end if;

  update public.member_notes
     set body       = v_new_body,
         updated_at = now()
   where id = p_note_id;

  insert into public.audit_log (club_id, actor_id, action, target_type, target_id, metadata)
  values (
    v_actor.club_id, auth.uid(), 'update_member_note', 'member_note', p_note_id,
    jsonb_build_object(
      'member_id', v_note.member_id,
      'old_body',  v_note.body,
      'new_body',  v_new_body
    )
  );
end;
$$;

alter function public.update_member_note(uuid, text) owner to postgres;
revoke execute on function public.update_member_note(uuid, text) from public, anon;
grant  execute on function public.update_member_note(uuid, text) to authenticated;
grant  execute on function public.update_member_note(uuid, text) to service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. archive_member_note — CREATE OR REPLACE (signature/return unchanged)
-- ═══════════════════════════════════════════════════════════════════════════
-- Argument name/type and return type (uuid -> void) are unchanged from
-- 0075/0077 — only the function BODY needs updating, to set is_archived
-- (the new canonical archived flag) alongside the existing archived_at/
-- archived_by/updated_at fields, and to check is_archived rather than
-- archived_at for the already-archived guard. CREATE OR REPLACE is safe
-- and sufficient here; ownership is untouched (never dropped).

create or replace function public.archive_member_note(
  p_note_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor public.profiles%rowtype;
  v_note  public.member_notes%rowtype;
begin
  select pr.* into v_actor from public.profiles pr where pr.id = auth.uid();
  if not found then raise exception 'not_authenticated'; end if;
  if v_actor.role <> 'admin' then raise exception 'insufficient_role'; end if;

  select mn.* into v_note from public.member_notes mn
   where mn.id      = p_note_id
     and mn.club_id = v_actor.club_id;
  if not found then raise exception 'note_not_found'; end if;
  if v_note.is_archived then raise exception 'note_already_archived'; end if;

  update public.member_notes
     set is_archived = true,
         archived_at = now(),
         archived_by = auth.uid(),
         updated_at  = now()
   where id = p_note_id;

  insert into public.audit_log (club_id, actor_id, action, target_type, target_id, metadata)
  values (
    v_actor.club_id, auth.uid(), 'archive_member_note', 'member_note', p_note_id,
    jsonb_build_object('member_id', v_note.member_id)
  );
end;
$$;

-- CREATE OR REPLACE preserves existing owner and grants automatically —
-- both restated explicitly anyway, matching this project's established
-- "don't rely on implicit persistence" convention (e.g. migrations
-- 0068/0166/0167). This is a no-op against current live (owner is already
-- postgres there) but makes canonical ownership explicit and independent
-- of who happens to run this migration.
alter function public.archive_member_note(uuid) owner to postgres;
revoke execute on function public.archive_member_note(uuid) from public, anon;
grant  execute on function public.archive_member_note(uuid) to authenticated;
grant  execute on function public.archive_member_note(uuid) to service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. PostgREST schema cache
-- ═══════════════════════════════════════════════════════════════════════════
-- No existing migration in this repository's history uses a NOTIFY pgrst
-- pattern (checked directly — zero matches for "pgrst"/"schema cache"/
-- "reload config" across all 210 prior migrations), so none is being
-- invented here beyond PostgREST's own standard, documented directive.
-- Supabase's hosted platform normally reloads PostgREST's schema cache
-- automatically via its own DDL event trigger; this NOTIFY makes that
-- explicit and immediate rather than relying on it silently, since RPC
-- ARGUMENT NAMES changing (p_content -> p_body) is exactly the kind of
-- change PostgREST must see before named-argument calls resolve correctly.
NOTIFY pgrst, 'reload schema';

commit;
